version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: template_dev
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  app:
    image: node:22
    container_name: template-backend
    restart: always
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: template_dev
      PORT: 8080 
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/src
    command: >
      sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run build && pnpm run start"
    depends_on:
      - postgres
    ports:
      - "8081:8080" 
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
